name: Create and publish lists
on:
  push:
    branches:
      - master
  schedule:
    - cron: '20 2 * * SAT'
  workflow_dispatch:

jobs:
  create-lists:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: "pip"
      - name: Install dependencies
        run: pip install -r scripts/requirements.txt
      - run: |
          python scripts/csv-to-json-gitlab.py
          python scripts/json-to-html-libs-gitlab.py
          python scripts/json-to-html-repos-gitlab.py
          python scripts/csv-to-json.py ${{ secrets.GITHUB_TOKEN }}
          python scripts/json-to-html-libs.py
          python scripts/json-to-html-repos.py
          mkdir .public
          cp -r static .public/
          cp {libraries-gitlab.html,repositories-gitlab.html,libraries.html,repositories.html} .public
          mv .public public
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: create-lists
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
